# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 96822693d58b443bc7b6dfebf3a4bac35fcfc7828e8ebea435e848e2fe8d48bee819e7be7e51358c6d1f534a3e58a10ca5518c1dc31cde84f1f1241b74e658fa

test:
  secret_key_base: 766783f5d7cdc046a550015faa8116561836cc0b10f0641d9a25e73b923e6d4e555e3027aa4e546f16d8064178ab7dca86c5d73b0f04f869bba7773c67a0050e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
